### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by krinkin** [myutman/project#1]
kkv@thinkpad:/ws/projects/au-capstone-2017/pp$ make
lex src/ypl.lex
g++ -O2 -Wall -std=c++11 -Iinclude -c -MMD -o bin/lex.yy.o lex.yy.c
src/ypl.lex: In function ‘int yylex()’:
src/ypl.lex:29:28: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 .    yyerror("Invalid character");
                            ^
lex.yy.c: In function ‘int yy_get_next_buffer()’:
lex.yy.c:1160:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                            ^
lex.yy.c: At global scope:
lex.yy.c:1236:17: warning: ‘void yyunput(int, char*)’ defined but not used [-Wunused-function]
     static void yyunput (int c, char * yy_bp )
                 ^
g++ bin/main.o bin/model.o bin/ypl.tab.o bin/lex.yy.o -o yc 
bin/lex.yy.o: In function `yylex()':
lex.yy.c:(.text+0x803): undefined reference to `yylval[abi:cxx11]'
lex.yy.c:(.text+0x810): undefined reference to `yylval[abi:cxx11]'
lex.yy.c:(.text+0x835): undefined reference to `yylval[abi:cxx11]'
lex.yy.c:(.text+0x842): undefined reference to `yylval[abi:cxx11]'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'yc' failed
make: *** [yc] Error 1

**Comment by myutman** [comment]
Теперь всё должно билдиться
